# Generated by Django 5.1.6 on 2025-05-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgapp", "0002_alter_restaurant_options_moderatorfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="review_images/",
                verbose_name="Yemek Fotoğrafı",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="receipt",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="review_receipts/",
                verbose_name="Fiş/Fatura",
            ),
        ),
    ]
