# Generated by Django 5.1.6 on 2025-04-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgapp", "0003_application"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="application_text",
        ),
        migrations.RemoveField(
            model_name="application",
            name="created_at",
        ),
        migrations.AddField(
            model_name="application",
            name="message",
            field=models.TextField(default="Belirtilmemiş"),
            preserve_default=False,
        ),
    ]
