# Generated by Django 5.1.6 on 2025-04-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgapp", "0004_remove_application_application_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_dish",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
